//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNA.Web.Sistema.Produto.Veicular {
    
    
    public partial class Home {
        
        /// <summary>
        /// ucProdutosVeiculares1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DNA.Web.Controles.Veicular.ucProdutosVeiculares ucProdutosVeiculares1;
    }
}
