//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace DNA.Negocios.WSDNARoteador {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RoteadorSoap", Namespace="http://tempuri.org/")]
    public partial class Roteador : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SISCOMPesquisaPFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Roteador() {
            this.Url = global::DNA.Negocios.Properties.Settings.Default.DNA_Negocios_WSDNARoteador_Roteador;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarUsuariosCompletedEventHandler ListarUsuariosCompleted;
        
        /// <remarks/>
        public event SISCOMPesquisaPFCompletedEventHandler SISCOMPesquisaPFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] ListarUsuarios(string chaveAcessoWSInterno, string idUsuario, string loginUsuario, string senhaUsuario, string flagAtivo) {
            object[] results = this.Invoke("ListarUsuarios", new object[] {
                        chaveAcessoWSInterno,
                        idUsuario,
                        loginUsuario,
                        senhaUsuario,
                        flagAtivo});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuariosAsync(string chaveAcessoWSInterno, string idUsuario, string loginUsuario, string senhaUsuario, string flagAtivo) {
            this.ListarUsuariosAsync(chaveAcessoWSInterno, idUsuario, loginUsuario, senhaUsuario, flagAtivo, null);
        }
        
        /// <remarks/>
        public void ListarUsuariosAsync(string chaveAcessoWSInterno, string idUsuario, string loginUsuario, string senhaUsuario, string flagAtivo, object userState) {
            if ((this.ListarUsuariosOperationCompleted == null)) {
                this.ListarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuariosOperationCompleted);
            }
            this.InvokeAsync("ListarUsuarios", new object[] {
                        chaveAcessoWSInterno,
                        idUsuario,
                        loginUsuario,
                        senhaUsuario,
                        flagAtivo}, this.ListarUsuariosOperationCompleted, userState);
        }
        
        private void OnListarUsuariosOperationCompleted(object arg) {
            if ((this.ListarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuariosCompleted(this, new ListarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SISCOMPesquisaPF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response SISCOMPesquisaPF(string chaveAcessoWSInterno, string CPF) {
            object[] results = this.Invoke("SISCOMPesquisaPF", new object[] {
                        chaveAcessoWSInterno,
                        CPF});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void SISCOMPesquisaPFAsync(string chaveAcessoWSInterno, string CPF) {
            this.SISCOMPesquisaPFAsync(chaveAcessoWSInterno, CPF, null);
        }
        
        /// <remarks/>
        public void SISCOMPesquisaPFAsync(string chaveAcessoWSInterno, string CPF, object userState) {
            if ((this.SISCOMPesquisaPFOperationCompleted == null)) {
                this.SISCOMPesquisaPFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSISCOMPesquisaPFOperationCompleted);
            }
            this.InvokeAsync("SISCOMPesquisaPF", new object[] {
                        chaveAcessoWSInterno,
                        CPF}, this.SISCOMPesquisaPFOperationCompleted, userState);
        }
        
        private void OnSISCOMPesquisaPFOperationCompleted(object arg) {
            if ((this.SISCOMPesquisaPFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SISCOMPesquisaPFCompleted(this, new SISCOMPesquisaPFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private int idUsuarioField;
        
        private System.Nullable<int> idClienteField;
        
        private string nomeUsuarioField;
        
        private string loginUsuarioField;
        
        private string senhaUsuarioField;
        
        private string email1Field;
        
        private string email2Field;
        
        private string observacaoField;
        
        private string flagAtivoField;
        
        private System.Nullable<System.DateTime> dataInclusaoField;
        
        private System.Nullable<int> idUsuarioInclusaoField;
        
        private System.Nullable<System.DateTime> dataAlteracaoField;
        
        private System.Nullable<int> idUsuarioAlteracaoField;
        
        private PerfilAcesso[] perfilField;
        
        private string ipClienteLogadoField;
        
        private Produto[] produtosField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string LoginUsuario {
            get {
                return this.loginUsuarioField;
            }
            set {
                this.loginUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaUsuario {
            get {
                return this.senhaUsuarioField;
            }
            set {
                this.senhaUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
            }
        }
        
        /// <remarks/>
        public string Email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        public string FlagAtivo {
            get {
                return this.flagAtivoField;
            }
            set {
                this.flagAtivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataInclusao {
            get {
                return this.dataInclusaoField;
            }
            set {
                this.dataInclusaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioInclusao {
            get {
                return this.idUsuarioInclusaoField;
            }
            set {
                this.idUsuarioInclusaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataAlteracao {
            get {
                return this.dataAlteracaoField;
            }
            set {
                this.dataAlteracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioAlteracao {
            get {
                return this.idUsuarioAlteracaoField;
            }
            set {
                this.idUsuarioAlteracaoField = value;
            }
        }
        
        /// <remarks/>
        public PerfilAcesso[] Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
            }
        }
        
        /// <remarks/>
        public string IpClienteLogado {
            get {
                return this.ipClienteLogadoField;
            }
            set {
                this.ipClienteLogadoField = value;
            }
        }
        
        /// <remarks/>
        public Produto[] Produtos {
            get {
                return this.produtosField;
            }
            set {
                this.produtosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerfilAcesso {
        
        private int idPerfilAcessoField;
        
        private int idUsuarioField;
        
        private int idPerfilAcessoUsuarioField;
        
        private string descricaoPerfilAcessoField;
        
        private System.Nullable<System.DateTime> dataInclusaoPerfilAcessoField;
        
        private System.Nullable<int> idUsuarioInclusaoPerfilAcessoField;
        
        private System.Nullable<System.DateTime> dataAlteracaoPerfilAcessoField;
        
        private System.Nullable<int> idUsuarioAlterasaoPerfilAcessoField;
        
        private string flagAtivoPerfilAcessoField;
        
        private string nomeUsuarioInclusaoField;
        
        private string nomeUsuarioAlteracaoField;
        
        /// <remarks/>
        public int IdPerfilAcesso {
            get {
                return this.idPerfilAcessoField;
            }
            set {
                this.idPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdPerfilAcessoUsuario {
            get {
                return this.idPerfilAcessoUsuarioField;
            }
            set {
                this.idPerfilAcessoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoPerfilAcesso {
            get {
                return this.descricaoPerfilAcessoField;
            }
            set {
                this.descricaoPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataInclusaoPerfilAcesso {
            get {
                return this.dataInclusaoPerfilAcessoField;
            }
            set {
                this.dataInclusaoPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioInclusaoPerfilAcesso {
            get {
                return this.idUsuarioInclusaoPerfilAcessoField;
            }
            set {
                this.idUsuarioInclusaoPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataAlteracaoPerfilAcesso {
            get {
                return this.dataAlteracaoPerfilAcessoField;
            }
            set {
                this.dataAlteracaoPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioAlterasaoPerfilAcesso {
            get {
                return this.idUsuarioAlterasaoPerfilAcessoField;
            }
            set {
                this.idUsuarioAlterasaoPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        public string FlagAtivoPerfilAcesso {
            get {
                return this.flagAtivoPerfilAcessoField;
            }
            set {
                this.flagAtivoPerfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeUsuarioInclusao {
            get {
                return this.nomeUsuarioInclusaoField;
            }
            set {
                this.nomeUsuarioInclusaoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeUsuarioAlteracao {
            get {
                return this.nomeUsuarioAlteracaoField;
            }
            set {
                this.nomeUsuarioAlteracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error {
        
        private string errorCodeField;
        
        private string fieldNameField;
        
        private string messageField;
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseError {
        
        private string errorCodeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Status {
        
        private int codeField;
        
        private System.Nullable<System.DateTime> dateTimeField;
        
        private string detailField;
        
        private string messageField;
        
        private System.Guid protocolField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Telefone {
        
        private int dDDField;
        
        private int numeroField;
        
        /// <remarks/>
        public int DDD {
            get {
                return this.dDDField;
            }
            set {
                this.dDDField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private string bairroField;
        
        private string cEPField;
        
        private string cidadeField;
        
        private string complementoField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string ufField;
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Email {
        
        private string enderecoField;
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosCadastrais {
        
        private string cPFField;
        
        private string nomeField;
        
        private string rgField;
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Output {
        
        private DadosCadastrais dadosCadastraisField;
        
        private Email[] emailsField;
        
        private Endereco[] enderecosField;
        
        private Telefone[] telefonesField;
        
        /// <remarks/>
        public DadosCadastrais DadosCadastrais {
            get {
                return this.dadosCadastraisField;
            }
            set {
                this.dadosCadastraisField = value;
            }
        }
        
        /// <remarks/>
        public Email[] Emails {
            get {
                return this.emailsField;
            }
            set {
                this.emailsField = value;
            }
        }
        
        /// <remarks/>
        public Endereco[] Enderecos {
            get {
                return this.enderecosField;
            }
            set {
                this.enderecosField = value;
            }
        }
        
        /// <remarks/>
        public Telefone[] Telefones {
            get {
                return this.telefonesField;
            }
            set {
                this.telefonesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InputItem {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response {
        
        private InputItem[] inputField;
        
        private Output outputField;
        
        private Status statusField;
        
        private ResponseError responseErrorField;
        
        /// <remarks/>
        public InputItem[] Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
        
        /// <remarks/>
        public Output Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ResponseError ResponseError {
            get {
                return this.responseErrorField;
            }
            set {
                this.responseErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Produto {
        
        private int idProdutoField;
        
        private int idPrecoProdutoField;
        
        private string nomeProdutoField;
        
        private string nomeInternoField;
        
        private string linkImagem1Field;
        
        private string linkImagem2Field;
        
        private string linkImagem3Field;
        
        private string linkNavegacaoWebField;
        
        private string descricaoProdutoField;
        
        private decimal precoProdutoField;
        
        private System.Nullable<decimal> descontoOferecidoPrecoProdutoField;
        
        private System.Nullable<System.DateTime> dataInicioVigenciaField;
        
        private System.Nullable<System.DateTime> dataFimVigenciaField;
        
        private System.Nullable<bool> flagAtivoProdutoField;
        
        private System.Nullable<bool> flagProdutoWebServiceField;
        
        private System.Nullable<bool> flagAtivoPrecoProdutoField;
        
        private System.Nullable<int> idUsuarioInclusaoProdutoField;
        
        private System.Nullable<int> idUsuarioAlteracaoProdutoField;
        
        private System.Nullable<int> idUsuarioInclusaoPrecoProdutoField;
        
        private System.Nullable<int> idUsuarioAlteracaoPrecoProdutoField;
        
        private System.Nullable<System.DateTime> dataInclusaoProdutoField;
        
        private System.Nullable<System.DateTime> dataAlteracaoProdutoField;
        
        private System.Nullable<System.DateTime> dataInclusaoPrecoProdutoField;
        
        private System.Nullable<System.DateTime> dataAlteracaoPrecoProdutoField;
        
        /// <remarks/>
        public int IdProduto {
            get {
                return this.idProdutoField;
            }
            set {
                this.idProdutoField = value;
            }
        }
        
        /// <remarks/>
        public int IdPrecoProduto {
            get {
                return this.idPrecoProdutoField;
            }
            set {
                this.idPrecoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeProduto {
            get {
                return this.nomeProdutoField;
            }
            set {
                this.nomeProdutoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeInterno {
            get {
                return this.nomeInternoField;
            }
            set {
                this.nomeInternoField = value;
            }
        }
        
        /// <remarks/>
        public string LinkImagem1 {
            get {
                return this.linkImagem1Field;
            }
            set {
                this.linkImagem1Field = value;
            }
        }
        
        /// <remarks/>
        public string LinkImagem2 {
            get {
                return this.linkImagem2Field;
            }
            set {
                this.linkImagem2Field = value;
            }
        }
        
        /// <remarks/>
        public string LinkImagem3 {
            get {
                return this.linkImagem3Field;
            }
            set {
                this.linkImagem3Field = value;
            }
        }
        
        /// <remarks/>
        public string LinkNavegacaoWeb {
            get {
                return this.linkNavegacaoWebField;
            }
            set {
                this.linkNavegacaoWebField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoProduto {
            get {
                return this.descricaoProdutoField;
            }
            set {
                this.descricaoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecoProduto {
            get {
                return this.precoProdutoField;
            }
            set {
                this.precoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DescontoOferecidoPrecoProduto {
            get {
                return this.descontoOferecidoPrecoProdutoField;
            }
            set {
                this.descontoOferecidoPrecoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataInicioVigencia {
            get {
                return this.dataInicioVigenciaField;
            }
            set {
                this.dataInicioVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataFimVigencia {
            get {
                return this.dataFimVigenciaField;
            }
            set {
                this.dataFimVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FlagAtivoProduto {
            get {
                return this.flagAtivoProdutoField;
            }
            set {
                this.flagAtivoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FlagProdutoWebService {
            get {
                return this.flagProdutoWebServiceField;
            }
            set {
                this.flagProdutoWebServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FlagAtivoPrecoProduto {
            get {
                return this.flagAtivoPrecoProdutoField;
            }
            set {
                this.flagAtivoPrecoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioInclusaoProduto {
            get {
                return this.idUsuarioInclusaoProdutoField;
            }
            set {
                this.idUsuarioInclusaoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioAlteracaoProduto {
            get {
                return this.idUsuarioAlteracaoProdutoField;
            }
            set {
                this.idUsuarioAlteracaoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioInclusaoPrecoProduto {
            get {
                return this.idUsuarioInclusaoPrecoProdutoField;
            }
            set {
                this.idUsuarioInclusaoPrecoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuarioAlteracaoPrecoProduto {
            get {
                return this.idUsuarioAlteracaoPrecoProdutoField;
            }
            set {
                this.idUsuarioAlteracaoPrecoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataInclusaoProduto {
            get {
                return this.dataInclusaoProdutoField;
            }
            set {
                this.dataInclusaoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataAlteracaoProduto {
            get {
                return this.dataAlteracaoProdutoField;
            }
            set {
                this.dataAlteracaoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataInclusaoPrecoProduto {
            get {
                return this.dataInclusaoPrecoProdutoField;
            }
            set {
                this.dataInclusaoPrecoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataAlteracaoPrecoProduto {
            get {
                return this.dataAlteracaoPrecoProdutoField;
            }
            set {
                this.dataAlteracaoPrecoProdutoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarUsuariosCompletedEventHandler(object sender, ListarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SISCOMPesquisaPFCompletedEventHandler(object sender, SISCOMPesquisaPFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SISCOMPesquisaPFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SISCOMPesquisaPFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591